### PR TITLE
Fixed Spelling Errors and did some more refactoring

### PR DESCRIPTION
**Pull request by Zrp200**

### CODE REVIEW

**Comment by Zrp200** [comment]
I don't think it is very smart to code directly on GitHub....

**Comment by Zrp200** [comment]
ok

**Comment by szymon33** [comment]
> I don't think it is very smart to code directly on GitHub....

I don't code directly on GitHub. What do you mean?

**Comment by Zrp200** [comment]
You have to commit each time you change a file. That's why I'm committing so much

**Comment by Zrp200** [comment]
This is not my finest hour

**Comment by szymon33** [comment]
@Zrp200 I hope you don't mind that I have just added your e-mail to Travis so you would know when you broke specs here.

**Comment by Zrp200** [comment]
Thanks

**Comment by Zrp200** [comment]
I haven't really coded in at least a year; I'm out of practice

**Comment by szymon33** [comment]
It has to be early in the morning in California so it should be your good
hour :smile: No problem, you can try here but please keep rspec passing or
watch Travis. If you write some new code always write tests. That's it. I
hope you know rspec.

**Comment by Zrp200** [comment]
Ok

**Comment by Zrp200** [comment]
finally

**Comment by szymon33** [comment]
Yep. Do you use Windows, Mac or Linux?

**Comment by Zrp200** [comment]
windows 10 as of last week

**Comment by szymon33** [comment]
Is something like `bundle exec rspec` or just `rspec` familiar for you? Works for you locally?

**Comment by Zrp200** [comment]
Yes, I've used it before. I haven't gotten build tools on here yet though. I'll be on again in a few hours :wave:

**Comment by Zrp200** [comment]
``` Failures:

  1) Game#control_loop with input from console when 'A5' changes status line
     Failure/Error: @matrix.each_with_index { |grow, index| Grid.row("#{AXE_LETTERS[index]} #{grow.join(' ')}") }

     NoMethodError:
       undefined method `join' for "-":String
     # ./lib/grid.rb:18:in `block in show'
     # ./lib/grid.rb:18:in `each'
     # ./lib/grid.rb:18:in `each_with_index'
     # ./lib/grid.rb:18:in `show'
     # ./lib/game.rb:69:in `show'
     # ./lib/game.rb:59:in `control_loop'
     # ./lib/game.rb:38:in `play'
     # ./spec/lib/game_spec.rb:166:in `block (6 levels) in <top (required)>'
     # ./spec/lib/game_spec.rb:166:in `block (5 levels) in <top (required)>'

Finished in 0.64206 seconds (files took 1.06 seconds to load)
72 examples, 1 failure

Failed examples:

rspec ./spec/lib/game_spec.rb:165 # Game#control_loop with input from console when 'A5' changes status line
```

**Comment by Zrp200** [comment]
I can't use bundler because your Gemfile keeps on rejecting my Ruby version

**Comment by Zrp200** [comment]
I didn't even change that file in 7f4ca55! Why didn't it catch that last time??

**Comment by szymon33** [comment]
@Zrp200:

> I can't use bundler because your Gemfile keeps on rejecting my Ruby version

Different applications might use different Ruby versions. It is impossible to keep just one Ruby for all applications in real live, isn't it? You should manage the problem using [Ruby environment](https://github.com/rbenv/rbenv) or [RVM](https://rvm.io)

If you can't do that then just temporary comment out ruby entry in your local `gemfile`.

**Pull request merged**
